--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022-11-11 6:45:03 AM
-- Server version: 5.7.27-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE `bank-app`;

--
-- Drop table `card`
--
DROP TABLE IF EXISTS card;

--
-- Set default database
--
USE `bank-app`;

--
-- Create table `card`
--
CREATE TABLE card (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  card_number varchar(10) binary NOT NULL,
  pin_type varchar(1) binary NOT NULL,
  pin_value varchar(255) binary NOT NULL,
  remain_count_block int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 41,
CHARACTER SET utf8,
CHECKSUM = 0,
COLLATE utf8_bin;

-- 
-- Dumping data for table card
--
INSERT INTO card VALUES
(1, '1055000001', '1', '1234', 2),
(2, '1055000002', '2', '12345678901234567890', 3),
(3, '1050500001', '1', '1111', 3);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;